#Include globally accessible parameters here
global:
    developer: Ravi Semwal
    db_connection_spec:  mongodb://localhost/heartbeat          #mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]